#!/bin/bash

## capture environment setup for upgrades
CONTAINER=eic_xl
TMPDIR=
VERSION=nightly
PREFIX=/direct/eic+u/tristan/eic
DISABLE_CVMFS_USAGE=

function print_the_help {
  echo "USAGE:  ./eic-shell [OPTIONS] [ -- COMMAND ]"
  echo "OPTIONAL ARGUMENTS:"
  echo "          -u,--upgrade    Upgrade the container to the latest version"
  echo "          -n,--no-cvmfs   Disable check for local CVMFS when updating. (D: enabled)"
  echo "          -c,--container  Container version (D: $CONTAINER) (requires cvmfs)"
  echo "          -v,--version    Version to install (D: $VERSION) (requires cvmfs)"
  echo "          -h,--help       Print this message"
  echo ""
  echo "  Start the eic-shell containerized software environment (Singularity version)."
  echo ""
  echo "EXAMPLES: "
  echo "  - Start an interactive shell: ./eic-shell" 
  echo "  - Upgrade the container:      ./eic-shell --upgrade"
  echo "  - Use different version:      ./eic-shell --version $(date +%y.%m).0-stable"
  echo "  - Execute a single command:   ./eic-shell -- <COMMAND>"
  echo ""
  exit
}

UPGRADE=

while [ $# -gt 0 ]; do
  key=$1
  case $key in
    -u|--upgrade)
      UPGRADE=1
      shift
      ;;
    -n|--no-cvmfs)
      DISABLE_CVMFS_USAGE=true
      shift
      ;;
    -c|--container)
      CONTAINER=$2
      export SIF=/cvmfs/singularity.opensciencegrid.org/eicweb/${CONTAINER}:${VERSION}
      shift
      shift
      ;;
    -v|--version)
      VERSION=$2
      export SIF=/cvmfs/singularity.opensciencegrid.org/eicweb/${CONTAINER}:${VERSION}
      shift
      shift
      ;;
    -h|--help)
      print_the_help
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "ERROR: unknown argument: $key"
      echo "use --help for more info"
      exit 1
      ;;
  esac
done

if [ ! -z ${UPGRADE} ]; then
  echo "Upgrading eic-shell..."
  if [ -z "$DISABLE_CVMFS_USAGE" -a -d /cvmfs/singularity.opensciencegrid.org/eicweb/${CONTAINER}:${VERSION} ]; then
    echo ""
    echo "Note: You cannot manually update the container as you are using the CVMFS version."
    echo "      The container will automatically update every 24 hours."
    echo "      You can override this by setting the '--no-cvmfs' flag, which will"
    echo "      instantiate a local version."
    echo "      This is only recommended for expert usage."
    echo ""
    echo "This will only upgrade the eic-shell script itself."
    echo ""
  fi
  FLAGS="-p ${PREFIX} -v ${VERSION}"
  if [ ! -z ${TMPDIR} ]; then
    FLAGS="${FLAGS} -t ${TMPDIR}"
  fi
  if [ ! -z ${DISABLE_CVMFS_USAGE} ]; then
    FLAGS="${FLAGS} --no-cvmfs"
  fi
  curl -L https://github.com/eic/eic-shell/raw/main/install.sh     | bash -s -- ${FLAGS}
  echo "eic-shell upgrade sucessful"
  exit 0
fi

export EIC_SHELL_PREFIX=/direct/eic+u/tristan/eic/local
export SINGULARITY_BINDPATH=/direct,/gpfs02,/gpfs01,/gpfs
echo $@
${SINGULARITY:-/usr/bin/singularity} exec ${SINGULARITY_OPTIONS:-} ${SIF:-/direct/eic+u/tristan/eic/local/lib/eic_xl-nightly} $@
